version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/TicketsBot/TicketsGo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get -v ./cmd/tickets/
      - run: go build cmd/tickets/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/TicketsGo/main
