version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/TicketsBot/TicketsGo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install czlib
          command: apt-get install -y zlib1g-dev

      - run: go build cmd/tickets/main.go

      - store_artifacts:
          path: /go/src/github.com/TicketsBot/TicketsGo/main
